- name: Create VPC  
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr_block }}"
    region: "{{ aws_region }}"
    state: "present"
  register: my_vpc

- name: Set VPC ID in variable
  set_fact:
    vpc_id: "{{ my_vpc.vpc.id }}"

- name: VPC ID Print
  debug: msg="{{ vpc_id }}"

- name: Save VPC ID into AWS VAR Config File
  lineinfile:
    path: "{{ aws_var_config_file }}"
    regexp: "^vpc_id:"
    line: "vpc_id: {{ vpc_id }}"
  when: my_vpc.changed